version: '3.9'

services:
  server:
    depends_on:
      - database
    build: .
    ports:
      - '5000:5000'
  database:
    image: 'postgres'
#     environment:
#       POSTGRES_PASSWORD: '123456'
#       POSTGRES_USER: 'docker'
#     volumes:
#       - data:/var/lib/postgresql/data

# volumes:
#   data:
